# need this to schedule an audit on the codebase daily
name: Security audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/cargo.toml"
      - "**/cargo.lock"

jobs:
  security_audit:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for Vulnerabilities
        run: cargo deny check advisories
